# Set bash to work with VI commands
set -o vi on

source ~/.config/profile/bash_aliases
# Load prompt configuration
source ~/.config/profile/shell_prompt.sh

eval `dircolors ~/.config/colours/dircolors-solarized.256dark`