GOPATH=$HOME/go

# Set bash to work with VI commands
set -o vi on

source ~/.config/profile/bash_aliases
# Load prompt configuration
source ~/.config/profile/shell_prompt.sh

eval `dircolors ~/.config/colours/dircolors-solarized.256dark`

function _update_ps1() {
    PS1="$($GOPATH/bin/powerline-go -error $?)"
}
if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi